"use client";
import {useEffect,useState} from 'react';
import {ArrowLeft,Save} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogFooter} from '@/components/ui/dialog';
import {type EventPlan} from '@/lib/event-model';
import {workbookProfit,divide} from '@/lib/workbook-calculations';
import type {recommendMedia} from '@/lib/media-recommendations';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import MediaAssistant from './media-assistant';
import mapping from '@/data/workbook-map.json';

const n=(v:number|null|undefined)=>v==null?'—':v.toLocaleString('ko-KR',{maximumFractionDigits:0});
const pct=(v:number|null|undefined)=>v==null?'—':(v*100).toFixed(2)+'%';
const won=(v:number|null|undefined)=>v==null?'자료 없음':n(v)+'원';
const keys=['qty','setting','discount','channel','own','revenue','sales','cost','costRate','gross','grossRate','fee','shipping','logistics','adRate','ad','profit','profitRate'];
const flavorOnly=(option:string)=>option.includes(' · ')?option.split(' · ').slice(1).join(' · '):option.replace(/^\d+(?:통|박스)\s*[·-]?\s*/, '');
function RevenueBars({target,actual}:{target:number|null|undefined,actual:number|null|undefined}){const max=Math.max(target??0,actual??0);return <div className="revenue-chart" aria-label={`목표 매출 ${won(target)}, 실제 매출 ${won(actual)}`}><div><span>목표 매출</span><i><b style={{width:max&&target!=null?`${Math.max(3,target/max*100)}%`:'0%'}}/></i><strong>{won(target)}</strong></div><div><span>실제 매출</span><i><b className="actual" style={{width:max&&actual!=null?`${Math.max(3,actual/max*100)}%`:'0%'}}/></i><strong>{won(actual)}</strong></div></div>}
function Input({label,value,onChange,rate=false}:{label:string,value:number|null|undefined,onChange:(v:number|null)=>void,rate?:boolean}){return <input className="cell-input" aria-label={label} type="number" min="0" max={rate?100:undefined} step={rate ? 0.01 : 'any'} value={value==null?'':rate?Number((value*100).toFixed(4)):value} onChange={e=>{const v=e.target.value===''?null:Number(e.target.value);if(v!=null&&(!Number.isFinite(v)||v<0||(rate&&v>100)))return;onChange(v==null?null:rate?v/100:v)}}/>}
export default function Operations({plan,onChange,onBack,onSave,onConfirm,busy,initialView='sales'}:{plan:EventPlan,onChange:(p:Partial<EventPlan>)=>void,onBack:()=>void,onSave:()=>void,onConfirm:()=>void,busy:boolean,initialView?:'sales'|'media'}){
 const [extraMedia,setExtraMedia]=useState<string[]>([]);
 const [view,setView]=useState<'sales'|'profit'|'media'>(initialView),[issue,setIssue]=useState<{title:string,issues:string[],source:string}|null>(null);
 useEffect(()=>setView(initialView),[initialView]);
 const [detail,setDetail]=useState(false),[formulas,setFormulas]=useState(false),[recommendations,setRecommendations]=useState<ReturnType<typeof recommendMedia>|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const result=workbookProfit(plan),lines=plan.lines.filter(l=>l.source==='스킴 선택');
 const cpcRecommendations=recommendations?.recommendations.filter(r=>!['플친','앱푸시','유상구좌(DA)','바이럴'].includes(r.name))??[];
 useEffect(()=>{document.getElementById('recent-events')?.scrollIntoView({block:'start'});},[]);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');setRecommendations(null);fetch(`/api/recommendations?channel=${encodeURIComponent(plan.channel)}&before=${plan.start}`,{signal:abort.signal}).then(async r=>{const d=await r.json() as ReturnType<typeof recommendMedia> & {error?:string};if(!r.ok)throw Error(d.error||'추천 조회 실패');return d}).then(setRecommendations).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!abort.signal.aborted)setLoading(false)});return()=>abort.abort()},[plan.channel,plan.start]);
 const changeLine=(index:number,patch:Partial<EventPlan['lines'][number]>)=>{const next=plan.lines.map(l=>l===lines[index]?{...l,...patch}:l);onChange({lines:next,...('planned' in patch?{targetQty:next.filter(l=>l.source==='스킴 선택').reduce((s,l)=>s+(l.planned??0),0)}:{})})};
 const changeMedia=(i:number,patch:Partial<EventPlan['media'][number]>)=>onChange({media:plan.media.map((m,j)=>{if(i!==j)return m;const cpc=patch.expectedCpc??m.expectedCpc??(m.target?m.budget/m.target:0),next={...m,...patch,expectedCpc:cpc};if('budget' in patch||'expectedCpc' in patch)next.target=cpc>0?Math.floor(next.budget/cpc):0;return next})});
 const format=(key:string,v:number|null)=>key.endsWith('Rate')?pct(v):n(v);
 return <div className="operations-page" data-view={view}><div className="section-head"><button className="btn" onClick={onBack}><ArrowLeft size={16}/>구성 품목 확인</button><button className="btn primary" onClick={onSave} disabled={busy}><Save size={16}/>{busy?'저장 중…':'웹에 저장'}</button></div>
 <p className="storage-note">저장 위치: 웹 내부 DB · 저장 후 ‘저장한 행사 불러오기’에서 불러올 수 있습니다. Google 시트 전송은 아직 연결하지 않았습니다.</p><div className="ops-switch" role="tablist" aria-label="운영 계획"><button role="tab" aria-selected={view==='sales'} onClick={()=>setView('sales')}>판매 수량 · 계산표</button><button role="tab" aria-selected={view==='profit'} onClick={()=>setView('profit')}>4-1 이익률 확인</button><button role="tab" aria-selected={view==='media'} onClick={()=>setView('media')}>CPC · 미디어 계획</button></div>
 <section id="recent-events" className="panel recent-panel"><h2>최근 유사 행사</h2><p className="muted">{plan.channel} · {plan.start} 이전 기록</p>{loading?<p role="status">조회 중…</p>:error?<p role="alert">{error}</p>:<div className="recent-cards">{recommendations?.recent.map((e,i)=><article key={e.id}><span>최근 유사 행사 {i+1}</span><h3>{e.title}</h3><small>{e.start.slice(0,10)} ~ {e.end.slice(0,10)}</small><RevenueBars target={e.targetRevenue} actual={e.revenue}/><dl><div><dt>실제 매출</dt><dd>{won(e.revenue)}</dd></div><div><dt>판매수량</dt><dd>{n(e.qty)}</dd></div><div><dt>공헌이익률</dt><dd>{pct(e.margin)}</dd></div><div><dt>ROAS</dt><dd>{pct(e.roas)}</dd></div></dl>{e.issues.length?<button className="btn quality-button" onClick={()=>setIssue({title:e.title,issues:e.issues,source:e.source})}>확인 요망 · {e.issues.length}항목</button>:<span className="quality-ok">기본 데이터 확인됨</span>}<details><summary>출처</summary>{e.source}</details></article>)}</div>}{!loading&&!error&&!recommendations?.recent.length&&<p className="muted">이 채널에 해당하는 과거 행사 자료가 없습니다.</p>}</section>
 <section className="panel ops-profit"><div className="section-head"><h2>4-1. 행사 이익률 계산</h2><button className="btn" onClick={()=>setFormulas(!formulas)}>{formulas?'수식 닫기':'엑셀 수식 보기'}</button></div><div className="fields"><label className="field">송장수량<Input label="송장수량" value={plan.invoiceCount??mapping.defaults.invoiceCount} onChange={v=>onChange({invoiceCount:v??0})}/></label><span className="fixed-field">객단가<b>{won(result.invoiceAverage)}</b></span></div><p className="footnote">목표 판매수량과 광고비율을 입력하면 원본 수식으로 자동 계산합니다. 목표 세팅가 매출과 수수료율은 첫 번째 확정 스킴을 기준으로 합니다. 단위: 원, %.</p><div className="formula-guide"><span><b>총 할인</b> ∑ 구성별 할인 × 수량</span><span><b>채널 부담</b> 총 할인 × (1−자사 분담률)</span><span><b>자사 부담</b> 총 할인 − 채널 부담</span><span><b>원가</b> ∑ 구성 원가 × 수량</span><span><b>원가율</b> 원가 ÷ 자사 매출가</span></div>{result.plannedQty!==plan.targetQty&&<p className="notice">4-2 예상 판매수량 합계 {n(result.plannedQty)}개 · 4-1 목표 {n(plan.targetQty)}개 <button className="btn" onClick={()=>onChange({targetQty:result.plannedQty??0})}>목표에 반영</button></p>}
 <div className="sheet-table"><table><thead><tr><th>항목</th><th>목표</th><th>달성</th><th>오차</th><th>달성률</th>{formulas&&<th>원본 수식 (목표 / 달성)</th>}</tr></thead><tbody>{mapping.profitRows.map((row,i)=>{const key=keys[i],p=result.target[key],a=result.actual[key];return <tr key={key}><th>{row.label}</th><td>{key==='qty'?<Input label="목표 판매수량" value={plan.targetQty} onChange={v=>onChange({targetQty:v??0})}/>:key==='adRate'?<Input label="목표 광고비율 %" value={plan.targetAdRate??mapping.defaults.targetAdRate} rate onChange={v=>onChange({targetAdRate:v??0})}/>:format(key,p)}</td><td>{key==='adRate'?<Input label="달성 광고비율 %" value={plan.actualAdRate??mapping.defaults.actualAdRate} rate onChange={v=>onChange({actualAdRate:v??0})}/>:format(key,a)}</td><td>{format(key,p==null||a==null?null:a-p)}</td><td>{pct(divide(a,p))}</td>{formulas&&<td className="formula-cell"><code>{String(row.target)}</code><br/><code>{String(row.actual)}</code></td>}</tr>})}</tbody></table></div></section>
 <section className="panel ops-sales"><div className="metrics-strip"><div><small>예상 판매수량</small><strong>{n(result.plannedQty)}개</strong></div><div><small>예상 × 세팅가 합계</small><strong>{won(result.detail.some(d=>d.X==null)?null:result.detail.reduce((s,d)=>s+(d.X??0),0))}</strong></div><div><small>예상 × 결제가 합계</small><strong>{won(result.detail.some(d=>d.Z==null)?null:result.detail.reduce((s,d)=>s+(d.Z??0),0))}</strong></div></div><div className="section-head"><h2>4-2. 판매 수량</h2><button className="btn primary" onClick={()=>setDetail(true)}>확인하기</button></div><p className="muted">노란 입력칸에 예상 판매 수량만 입력해 주세요.</p><div className="sheet-table"><table><thead><tr><th>품목</th><th>플레이버 · 구성</th><th>세팅가</th><th>소비자 결제가</th><th>예상 판매 수량</th><th>예상 × 세팅가</th><th>예상 × 결제가</th><th>예상 × 원가</th><th>실 판매량</th></tr></thead><tbody>{lines.map((l,i)=><tr key={`${l.group}-${l.option}`}><th>{l.group}</th><td>{flavorOnly(l.option)}</td><td>{n(result.detail[i].Q)}</td><td>{n(l.price)}</td><td><Input label={`${l.option} 예상 판매 수량`} value={l.planned} onChange={v=>changeLine(i,{planned:v})}/></td><td>{n(result.detail[i].X)}</td><td>{n(result.detail[i].Z)}</td><td>{n(result.detail[i].AA)}</td><td><Input label={`${l.option} 실 판매량`} value={l.actual} onChange={v=>changeLine(i,{actual:v})}/></td></tr>)}</tbody><tfoot><tr><th colSpan={4}>합계</th><td>{n(result.plannedQty)}</td>{(["X","Z","AA"] as const).map(k=><td key={k}>{n(result.detail.some(d=>d[k]==null)?null:result.detail.reduce((s,d)=>s+(d[k]??0),0))}</td>)}<td>{n(result.actualQty)}</td></tr></tfoot></table></div></section>
 <section className="panel ops-media"><h2>5. 전환/트래픽 목표</h2><div className="sheet-table"><table><thead><tr><th></th><th>구매전환율 (%)</th><th>트래픽</th><th>오차</th></tr></thead><tbody><tr><th>목표</th><td><Input label="목표 구매전환율 %" value={plan.targetConversion} rate onChange={v=>onChange({targetConversion:v??0})}/></td><td>{n(result.targetTraffic)}</td><td>{pct((plan.actualConversion??0)-(plan.targetConversion??0))}</td></tr><tr><th>달성</th><td><Input label="달성 구매전환율 %" value={plan.actualConversion} rate onChange={v=>onChange({actualConversion:v??0})}/></td><td><Input label="달성 트래픽" value={plan.actualTraffic} onChange={v=>onChange({actualTraffic:v??0})}/></td><td>{n(result.targetTraffic==null?null:plan.actualTraffic-result.targetTraffic)}</td></tr></tbody></table></div><p className="footnote">목표 트래픽 = 목표 판매수량 ÷ 입력한 구매전환율. 전환율이 0이면 계산하지 않습니다.</p></section>
 <section className="panel ops-media"><MediaAssistant channel={plan.channel} before={plan.start} budget={plan.media.reduce((s,m)=>s+m.budget,0)}/><h2>매체 추천 · 예상 CPC</h2><p className="footnote">{recommendations?.note}</p>{loading?<p>조회 중…</p>:error?<p role="alert">{error}</p>:!cpcRecommendations.length?<p>추천 데이터 준비 중입니다.</p>:<div className="sheet-table"><table><thead><tr><th>추천 매체</th><th>예상 CPC (유입 기준)</th><th>관측 범위</th><th>근거</th><th></th></tr></thead><tbody>{cpcRecommendations.map((r,i)=><tr key={r.name}><th>{i+1}. {r.name}</th><td>{won(r.expectedCpc)}</td><td>{won(r.minCpc)} ~ {won(r.maxCpc)}</td><td><details><summary>{r.reason}</summary>{r.sources.map((s,j)=><p key={j}>{s.date.slice(0,10)} {s.title}: {won(s.cost)} ÷ {n(s.traffic)}<br/>{s.source}</p>)}</details></td><td><button className="btn" onClick={()=>{const index=plan.media.findIndex(m=>m.name===r.name);if(index<0)onChange({media:[...plan.media,{name:r.name,budget:0,target:0,spent:0,actual:0,expectedCpc:r.expectedCpc}]});else changeMedia(index,{expectedCpc:r.expectedCpc});document.getElementById('media-plan')?.scrollIntoView({behavior:'smooth'})}}>계획에 추가</button></td></tr>)}</tbody></table></div>}</section>
 <section id="media-plan" className="panel ops-media"><div className="section-head"><div><h2>6. 미디어믹스 · 광고비</h2><p className="muted">계획 비용과 예상 CPC를 입력하면 목표 트래픽이 자동 계산됩니다.</p></div><Select value="" onValueChange={name=>setExtraMedia(v=>[...v,name])}><SelectTrigger style={{width:220}}><SelectValue placeholder="+ 매체 추가"/></SelectTrigger><SelectContent>{plan.media.filter(m=>!extraMedia.includes(m.name)&&!m.budget&&!m.spent&&!m.target&&!m.actual&&!m.expectedCpc).map(m=><SelectItem key={m.name} value={m.name}>{m.name}</SelectItem>)}</SelectContent></Select></div><div className="sheet-table"><table><thead><tr><th>매체</th><th>계획 비용</th><th>예상 CPC</th><th>목표 트래픽</th><th>실행 비용</th><th>CPC</th><th>실행 트래픽</th></tr></thead><tbody>{plan.media.map((m,i)=>{if(!extraMedia.includes(m.name)&&!m.budget&&!m.spent&&!m.target&&!m.actual&&!m.expectedCpc)return null;return <tr key={m.name}><th>{m.name}</th><td><Input label={`${m.name} 계획 비용`} value={m.budget||null} onChange={v=>changeMedia(i,{budget:v??0})}/></td><td><Input label={`${m.name} 예상 CPC`} value={m.expectedCpc?Number(m.expectedCpc.toFixed(2)):null} onChange={v=>changeMedia(i,{expectedCpc:v??0})}/></td><td><strong aria-label={`${m.name} 목표 트래픽`}>{m.target?n(m.target):'—'}</strong></td><td><Input label={`${m.name} 실행 비용`} value={m.spent||null} onChange={v=>changeMedia(i,{spent:v??0})}/></td><td><strong aria-label={`${m.name} 실행 CPC`}>{m.spent&&m.actual?won(m.spent/m.actual):'—'}</strong></td><td><Input label={`${m.name} 실행 트래픽`} value={m.actual||null} onChange={v=>changeMedia(i,{actual:v??0})}/></td></tr>})}</tbody><tfoot><tr><th>TOTAL</th><td>{plan.media.some(m=>m.budget)?n(plan.media.reduce((s,m)=>s+m.budget,0)):'—'}</td><td>—</td><td>{plan.media.some(m=>m.target)?n(plan.media.reduce((s,m)=>s+m.target,0)):'—'}</td><td>{plan.media.some(m=>m.spent)?n(plan.media.reduce((s,m)=>s+m.spent,0)):'—'}</td><td>{won(divide(plan.media.reduce((s,m)=>s+m.spent,0),plan.media.reduce((s,m)=>s+m.actual,0)))}</td><td>{plan.media.some(m=>m.actual)?n(plan.media.reduce((s,m)=>s+m.actual,0)):'—'}</td></tr></tfoot></table></div><p className="footnote">목표 트래픽 = 계획 비용 ÷ 예상 CPC · 실행 CPC = 실행 비용 ÷ 실행 트래픽</p></section>
 <div className="stage-next"><span>웹에 저장하면 ‘저장한 행사 불러오기’에서 이어서 편집할 수 있습니다.</span><div className="actions"><button className="btn" disabled={busy} onClick={onSave}>웹에 임시 저장</button><button className="btn primary" disabled={busy} onClick={onConfirm}>행사 확정 · 웹 저장</button></div></div>
 <Dialog open={!!issue} onOpenChange={v=>{if(!v)setIssue(null)}}><DialogContent><DialogHeader><DialogTitle>확인 요망 · {issue?.title}</DialogTitle><DialogDescription>원본에서 아래 항목을 확인한 뒤 비교 자료로 사용하세요.</DialogDescription></DialogHeader><ul>{issue?.issues.map(x=><li key={x}>{x}</li>)}</ul><p className="footnote">{issue?.source}</p><DialogFooter><button className="btn primary" onClick={()=>setIssue(null)}>확인</button></DialogFooter></DialogContent></Dialog>
 <Dialog open={detail} onOpenChange={setDetail}><DialogContent className="sales-detail-modal"><DialogHeader><DialogTitle>판매리스트 · 예상/실제 판매 계산</DialogTitle></DialogHeader><div className="sheet-table"><table><thead><tr>{mapping.salesColumns.map(c=><th key={c.column}>{c.label}</th>)}</tr></thead><tbody>{lines.map((l,i)=>{const d=result.detail[i],cells:Record<string,number|null>={...d,W:divide(l.planned,result.plannedQty),AG:divide(l.actual,result.actualQty)};cells.AH=cells.AG==null||cells.W==null?null:cells.AG-cells.W;return <tr key={i}>{mapping.salesColumns.map(c=><td key={c.column}>{c.column==='O'?l.group:c.column==='P'?flavorOnly(l.option):c.column==='V'||c.column==='AB'?<Input label={`${l.option} ${c.label}`} value={c.column==='V'?l.planned:l.actual} onChange={v=>changeLine(i,c.column==='V'?{planned:v}:{actual:v})}/>:c.column==='AI'?String(l.block+1):['W','AG','AH'].includes(c.column)?pct(cells[c.column]):n(cells[c.column])}</td>)}</tr>})}</tbody><tfoot><tr>{mapping.salesColumns.map((c,i)=><td key={c.column}>{i===0?'합계':['V','X','Y','Z','AA','AB','AC','AD','AE','AF'].includes(c.column)?n(result.detail.some(d=>d[c.column as keyof typeof d]==null)?null:result.detail.reduce((s,d)=>s+(d[c.column as keyof typeof d]??0),0)):''}</td>)}</tr></tfoot></table></div><DialogFooter><button className="btn primary" onClick={()=>setDetail(false)}>확인 완료</button></DialogFooter></DialogContent></Dialog>
 </div>
}
