"use client";
import {useState} from 'react';
import {toast} from 'sonner';
import {type EventPlan} from '@/lib/event-model';
import {workbookProfit} from '@/lib/workbook-calculations';
export default function PerformanceForm({plan,onSaved}:{plan:EventPlan,onSaved:(data:any)=>void}){
 const [draft,setDraft]=useState(plan),[busy,setBusy]=useState(false),result=workbookProfit(draft).actual;
 const input=(label:string,value:number|null,change:(v:number|null)=>void)=><input aria-label={label} type="number" min="0" value={value??''} onChange={e=>change(e.target.value===''?null:Math.max(0,Number(e.target.value)))}/>;
 async function save(){setBusy(true);try{const r=await fetch('/api/performance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:plan.id,version:plan.version,actual:draft.lines.map(l=>l.actual),invoiceCount:draft.invoiceCount??0,actualTraffic:draft.actualTraffic,actualConversion:draft.actualConversion??0,actualAdRate:draft.actualAdRate??0,media:draft.media.map(m=>({spent:m.spent,actual:m.actual}))})}),d:any=await r.json();if(!r.ok)throw Error(d.error);onSaved(d);toast.success('확정 조건을 유지하고 실적을 저장했습니다.')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel"><h2>확정 후 실적 입력</h2><p className="muted">가격과 스냅샷은 유지하고 판매 수량·트래픽·광고 실적만 추가합니다.</p><div className="sheet-table"><table><thead><tr><th>구성</th><th>실 판매수량</th></tr></thead><tbody>{draft.lines.map((l,i)=>l.source==='스킴 선택'&&<tr key={i}><th>{l.group} · {l.option}</th><td>{input(l.option+' 실적',l.actual,v=>setDraft(d=>({...d,lines:d.lines.map((x,j)=>i===j?{...x,actual:v}:x)})))}</td></tr>)}</tbody></table></div><div className="fields">{(['invoiceCount','actualTraffic','actualConversion','actualAdRate'] as const).map((k,i)=><label className="field" key={k}>{['송장수량','실제 트래픽','실제 구매전환율 (%)','달성 광고비율 (%)'][i]}{input(k,(draft[k]??0)*(i>1?100:1),v=>setDraft(d=>({...d,[k]:(v??0)/(i>1?100:1)})))}</label>)}</div><div className="sheet-table"><table><thead><tr><th>매체</th><th>실행 광고비</th><th>실제 트래픽</th></tr></thead><tbody>{draft.media.map((m,i)=><tr key={i}><th>{m.name}</th>{(['spent','actual'] as const).map(k=><td key={k}>{input(m.name+k,m[k],v=>setDraft(d=>({...d,media:d.media.map((x,j)=>i===j?{...x,[k]:v??0}:x)})))}</td>)}</tr>)}</tbody></table></div><p>실제 매출: {result.revenue?.toLocaleString('ko-KR')??'—'}원 · 공헌이익: {result.profit?.toLocaleString('ko-KR')??'—'}원</p><button className="btn primary" disabled={busy} onClick={save}>{busy?'저장 중…':'실적 저장'}</button></section>
}
