"use client";
import './responsive-workspace.css';
import './event-design.css';
import './event-enhancements.css';
import {useEffect,useMemo,useState} from 'react';
import {toast} from 'sonner';
import {ArrowLeft,Check,Search,Save} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {eventSchema,settlement,type EventPlan} from '@/lib/event-model';
import {makeTemplate} from '@/lib/template';
import type {Source} from './workspace';
import Operations from './operations';
import PerformanceForm from './performance-form';
import SnapshotPanel from './snapshot-panel';
import EventToolbar,{type SavedPlan} from './event-toolbar';

const money=(v:number|undefined|null)=>v==null?'확인 필요':v.toLocaleString('ko-KR',{maximumFractionDigits:0})+'원';
const number=(v:number|undefined|null)=>v==null?'—':v.toLocaleString('ko-KR',{maximumFractionDigits:0});
const percent=(v:number|undefined|null)=>v==null?'—':(v*100).toFixed(2)+'%';
const Field=({label,value,onChange,type='text',disabled=false}:{label:string,value:string|number,onChange:(v:any)=>void,type?:string,disabled?:boolean})=><label className="field">{label}<input type={type} value={value} min={type==='number'?0:undefined} disabled={disabled} onChange={x=>onChange(type==='number'?Number(x.target.value):x.target.value)}/></label>;
const Pick=({label,value,options,onChange}:{label:string,value:string,options:string[],onChange:(v:string)=>void})=><label className="field">{label}<Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem value={v} key={v}>{v}</SelectItem>)}</SelectContent></Select></label>;

function FeeCard({plan,index,option,guide,benefit,gift}:{plan:EventPlan,index:number,option:string,guide:number,benefit:number,gift:string}){
 const block=plan.blocks[index],initial=guide?settlement(guide,block):null,finalPrice=guide+benefit,final=finalPrice?settlement(finalPrice,block):null;
 const effective=(r:typeof initial)=>r&&r.setting?(r.fee-r.ownDiscount)/(r.setting-r.ownDiscount-r.channelDiscount):null;
 return <section className="panel calculator-hero fee-card"><h2>수수료 계산기</h2><p className="muted">{block.name} · {option} 기준</p><div className="scheme-grid"><div><h3>체감 수수료 계산</h3><p>세팅가 <b>{money(initial?.setting)}</b></p><p>채널 부담 할인 <b className="red">{money(initial?.channelDiscount)}</b></p><p>자사 부담 할인 <b className="red">{money(initial?.ownDiscount)}</b></p><p>소비자 결제가 <b>{money(guide)}</b></p></div><div><h3>&nbsp;</h3><p>자사 매출가 <b>{money(initial?.sales)}</b></p><p>수수료 <b className="red">{money(initial?.fee)}</b></p><p>정산액 <b>{money(initial?.settled)}</b></p><p>체감 수수료 <b className="red">{money(initial?(initial.fee-initial.ownDiscount):undefined)}</b></p></div></div><div className="benefit-grid"><h3>혜택 확정</h3><p>체감 수수료율 <b>{effective(initial)==null?'확인 필요':percent(effective(initial))}</b></p><p>가격 가이드 <b>{money(guide)}</b></p><p>혜택 가격 조정 <b className="red">{benefit.toLocaleString('ko-KR')}원</b></p><p>상품 증정 <b>{gift||'X'}</b></p></div><div className="scheme-grid final-scheme"><div><h3>최종 행사 스킴</h3><p>세팅가 <b>{money(final?.setting)}</b></p><p>채널 부담 할인 <b className="red">{money(final?.channelDiscount)}</b></p><p>자사 부담 할인 <b className="red">{money(final?.ownDiscount)}</b></p><p>소비자 결제가 <b>{money(finalPrice)}</b></p></div><div><h3>&nbsp;</h3><p>자사 매출가 <b>{money(final?.sales)}</b></p><p>수수료 <b className="red">{money(final?.fee)}</b></p><p>정산액 <b>{money(final?.settled)}</b></p><p>최종 수수료율 <b>{effective(final)==null?'확인 필요':percent(effective(final))}</b></p></div></div><p className="footnote">세팅가 = 소비자 결제가 ÷ (1−할인율) · 수수료 = {block.basis} × 수수료율 · 체감 수수료율 = (수수료−자사 부담 할인) ÷ 소비자 결제가</p></section>
}

export default function Planner({sources}:{sources:Source[]}){
 const [e,setE]=useState<EventPlan>(()=>makeTemplate(sources));
 const [stage,setStage]=useState(0);
 const [confirmation,setConfirmation]=useState<{message:string,action:()=>void}|null>(null);
 const [snapshot,setSnapshot]=useState<any>(null),[audit,setAudit]=useState<any[]>([]);
 const [saveLabel,setSaveLabel]=useState('아직 저장하지 않음');
 const [savedPlans,setSavedPlans]=useState<SavedPlan[]>([]),[loadId,setLoadId]=useState('');
 useEffect(()=>{setE(v=>({...v,id:crypto.randomUUID()}));fetch('/api/events').then(r=>r.ok?r.json():[]).then(d=>setSavedPlans(d as SavedPlan[])).catch(()=>{})},[]);
 async function loadPlan(id=loadId){if(!id)return;try{const r=await fetch(`/api/events?id=${encodeURIComponent(id)}`),d:any=await r.json();if(!r.ok)throw Error(d.error);const parsed=eventSchema.parse(d);setE(parsed);setSnapshot(d.snapshot);setAudit(d.audit??[]);setSaveLabel(`저장됨 · ${d.updatedAt||''}`);setGroup(parsed.blocks[0].name);setOption(parsed.blocks[0].composition);setChannelExtra(parsed.blocks[0].channelExtra??'X');setGiftExtra(parsed.blocks[0].gift==='O'?'O':'X');setUniformExtra(parsed.blocks[0].uniform==='O'?'O':'X');setConfirmed(parsed.lines.some(l=>l.source==='스킴 선택'));setDetailPage(false);setStage(1)}catch(x){toast.error((x as Error).message)}}
 const [busy,setBusy]=useState(false),[group,setGroup]=useState(e.blocks[0].name),[option,setOption]=useState('1통'),[channelExtra,setChannelExtra]=useState('X'),[giftExtra,setGiftExtra]=useState('X'),[uniformExtra,setUniformExtra]=useState('X'),[selectedChoices,setSelectedChoices]=useState<string[]>([]),[surcharges,setSurcharges]=useState<Record<string,number>>({}),[bulkSurcharge,setBulkSurcharge]=useState(0),[flavorQuery,setFlavorQuery]=useState(''),[flavorOpen,setFlavorOpen]=useState(false),[confirmed,setConfirmed]=useState(false),[detailPage,setDetailPage]=useState(false);
 const change=(p:Partial<EventPlan>)=>{if(e.status==='완료'){toast.error('확정된 행사는 복사 후 편집하세요.');return}setSaveLabel('저장되지 않은 변경 사항');setE(v=>({...v,...p,status:'진행중'}))};
 const channelRows=sources.find(s=>s.name.includes('CHANNEL_DB'))!.rows.slice(1),channels=useMemo(()=>Array.from(new Set([...channelRows.map(r=>String(r.cells.B)),e.channel])),[channelRows,e.channel]);
 const raw=sources.find(s=>s.name==='RAW')!.rows,products=sources.find(s=>s.name.includes('PRODUCT_DB'))!.rows.slice(1),costs=sources.find(s=>s.name.includes('COST_DB'))!.rows.slice(1),performance=sources.find(s=>s.name.includes('PERFORMANCE_DB'))?.rows.slice(1)||[];
 const selected=Math.max(0,e.blocks.findIndex(b=>b.name===group)),block=e.blocks[selected],compositions=(group.includes('파우치')||group.includes('인박스')||group.includes('바'))?['1박스','2박스']:['1통','2통','3통'];
 const productFlavors=products.filter(r=>String(r.cells.B)===group).map(r=>String(r.cells.D).replace('맛','')).filter((v,i,a)=>v&&a.indexOf(v)===i),cycle=e.blocks[0].cycle,period=e.blocks[0].period,rawMatch=raw.find(r=>r.cells.A===group&&r.cells.B===option&&r.cells.C===cycle&&r.cells.D===period&&block.fee>=Number(r.cells.E)&&block.fee<=Number(r.cells.F));
 const guide=Number(rawMatch?.cells.G)||0,benefit=(channelExtra==='O'?-1000:0)+(giftExtra==='O'?1000:0)+(uniformExtra==='O'?1000:0),unit=Number(option[0])||1;
 const schemeOptions=group==='바'&&option==='2박스'?['피넛버터맛 2','초코맛 2','피넛버터맛 + 초코맛']:unit===2?[...productFlavors.map(f=>`${f}2`),...productFlavors.flatMap((f,i)=>productFlavors.slice(i+1).map(g=>`${f}+${g}`))]:productFlavors.map(f=>unit>1?`${f}${unit}`:f),visibleOptions=schemeOptions.filter(x=>x.toLowerCase().includes(flavorQuery.toLowerCase()));
 const cycleOptions=Array.from(new Set(raw.filter(r=>r.cells.A===group&&r.cells.B===option).map(r=>String(r.cells.C)).filter(Boolean))),periodOptions=Array.from(new Set(raw.filter(r=>r.cells.A===group&&r.cells.B===option&&r.cells.C===cycle).map(r=>String(r.cells.D)).filter(Boolean)));
 const isReference=(choice:string)=>group==='대용량'&&choice.replace(/[\s\d]/g,'').replace(/맛/g,'')==='곡물';
 const fixedForChannel=(channel:string)=>{const row=channelRows.find(r=>r.cells.B===channel),basis=row?.cells.C;change({channel,blocks:e.blocks.map(b=>({...b,basis:(basis||b.basis) as typeof b.basis}))});if(row?.cells.E&&window.confirm(`${channel} 행사 시트로 이동할까요?`))window.open(String(row.cells.E),'_blank','noopener,noreferrer')};
 useEffect(()=>{setSelectedChoices([]);setSurcharges({});setBulkSurcharge(0);setFlavorQuery('');setFlavorOpen(false)},[group]);
 async function save(finalize=false){const candidate={...e,status:finalize?'완료':e.status};const parsed=eventSchema.safeParse(candidate);if(!parsed.success){toast.error(parsed.error.issues[0].message);return}setBusy(true);try{const r=await fetch('/api/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(candidate)}),d:any=await r.json();if(!r.ok)throw Error(d.error);setE(v=>({...v,version:d.version,status:d.status}));setSnapshot(d.snapshot);setAudit(d.audit??[]);setSaveLabel('저장됨 · '+d.updatedAt);fetch('/api/events').then(r=>r.json()).then(d=>setSavedPlans(d as SavedPlan[]));toast.success(finalize?'행사 스냅샷을 확정했습니다.':'행사를 저장했습니다.')}catch(x){toast.error((x as Error).message)}finally{setBusy(false)}}
 function reset(keep:boolean){const next=keep?{...e}:makeTemplate(sources);setE({...next,id:crypto.randomUUID(),version:0,status:'대기',lines:[],targetQty:0,actualTraffic:0,media:next.media.map(m=>({...m,budget:0,spent:0,target:0,actual:0}))});setSelectedChoices([]);setSurcharges({});setChannelExtra('X');setGiftExtra('X');setUniformExtra('X');setConfirmed(false);setDetailPage(false);setStage(0);setSaveLabel('아직 저장하지 않음')}
 function copy(){setE(v=>({...v,id:crypto.randomUUID(),version:0,status:'진행중',title:v.title+' (복사)'}));setSaveLabel('복사됨 · 저장 필요');setDetailPage(false)}

 function openFlavors(){const saved=e.lines.filter(l=>l.source==='스킴 선택'&&l.block===selected&&l.option.startsWith(option+' · '));setSelectedChoices(saved.map(l=>l.option.slice((option+' · ').length)));setSurcharges(Object.fromEntries(saved.map(l=>[l.option.slice((option+' · ').length),Math.max(0,(l.price??0)-(l.basePrice??guide+benefit))])));setFlavorQuery('');setFlavorOpen(true)}
 function saveSchemes(){if(!Number.isFinite(guide)||guide<=0){toast.error('가격 가이드가 있는 행사 조건을 먼저 선택해 주세요.');return}if(!selectedChoices.length){toast.error('구성을 하나 이상 선택해 주세요.');return}const current=e.lines.filter(l=>l.source==='스킴 선택'&&l.block===selected&&l.option.startsWith(`${option} · `)),kept=e.lines.filter(l=>!current.includes(l)),next=selectedChoices.map(choice=>{const name=`${option} · ${choice}`,previous=current.find(l=>l.option===name),parts=choice.split('+').map(v=>v.trim()),cost=parts.reduce((sum,part)=>{const count=Number(part.match(/\d+$/)?.[0])||1,flavor=part.replace(/\s*\d+$/,'').replace('맛',''),costGroup=group==='파우치'&&option.includes('박스')?'인박스':group,row=raw.find(r=>r.cells.S===costGroup&&String(r.cells.T).replace('맛','')===flavor);return row&&typeof row.cells.U==='number'?sum+row.cells.U*(costGroup!==group?1:Number(row.cells.V)||1)*count:NaN},0);return{group:block.name,option:name,block:selected,basePrice:guide+benefit,price:guide+benefit+(isReference(choice)?0:surcharges[choice]||0),cost:Number.isFinite(cost)?cost:null,planned:previous?.planned??0,actual:previous?.actual??null,source:'스킴 선택'}});change({lines:[...kept,...next],blocks:e.blocks.map((b,i)=>i===selected?{...b,composition:option,guide,channelExtra:channelExtra as 'O'|'X',gift:giftExtra,uniform:uniformExtra}:b)});setFlavorOpen(false);setConfirmed(true);setTimeout(()=>document.getElementById('sales-plan')?.scrollIntoView({behavior:'smooth'}),0)}
 const journey=<nav className="journey" aria-label="행사 만들기">{['행사 조건','가격 · 맛 구성','판매 · 이익 계획','미디어 · 저장'].map((label,i)=><button key={label} aria-current={stage===i?'step':undefined} onClick={()=>{if(i>1&&!e.lines.some(l=>l.source==='스킴 선택')){toast.error('먼저 가격을 확인하고 맛 구성을 저장하세요.');return}setStage(i);setDetailPage(i>1);window.scrollTo({top:0,behavior:'smooth'})}}><b>{i+1}</b><span>{label}</span></button>)}</nav>;
 const confirmationDialog=<Dialog open={!!confirmation} onOpenChange={open=>{if(!open)setConfirmation(null)}}><DialogContent><DialogHeader><DialogTitle>작업 확인</DialogTitle><DialogDescription>{confirmation?.message}</DialogDescription></DialogHeader><DialogFooter><button className="btn" onClick={()=>setConfirmation(null)}>취소</button><button className="btn primary" onClick={()=>{const action=confirmation?.action;setConfirmation(null);action?.()}}>확인</button></DialogFooter></DialogContent></Dialog>;
 if(e.status==='완료')return <><EventToolbar plan={e} items={savedPlans} saved={saveLabel} busy={busy} onNew={()=>setConfirmation({message:'새 행사로 시작할까요? 저장된 행사는 삭제하지 않습니다.',action:()=>reset(false)})} onReset={()=>setConfirmation({message:'기본정보를 유지하고 상품·수량·광고 계획을 초기화할까요?',action:()=>reset(true)})} onCopy={copy} onLoad={id=>setConfirmation({message:'현재 화면 대신 저장된 행사를 불러올까요?',action:()=>{loadPlan(id)}})} onConfirm={()=>setConfirmation({message:'현재 조건과 계산 결과를 확정할까요? 확정 후에는 복사해서 편집할 수 있습니다.',action:()=>{save(true)}})}/><SnapshotPanel snapshot={snapshot} audit={audit}/><PerformanceForm key={e.id} plan={e} onSaved={d=>{setE(eventSchema.parse(d));setSnapshot(d.snapshot);setAudit(d.audit??[]);setSaveLabel("실적 저장됨 · "+d.updatedAt)}}/>{confirmationDialog}</>;
 if(detailPage)return <>{journey}<Operations plan={e} onChange={change} onBack={()=>{setDetailPage(false);setStage(1)}} onSave={()=>save()} onConfirm={()=>setConfirmation({message:'현재 조건과 계산 결과를 웹 DB에 확정 저장할까요? Google 시트에는 전송되지 않습니다.',action:()=>{save(true)}})} busy={busy} initialView={stage===3?'media':'sales'}/>{confirmationDialog}</>;
 return <>{journey}<div className={`editor-stage stage-${stage}`}><EventToolbar plan={e} items={savedPlans} saved={saveLabel} busy={busy} onNew={()=>setConfirmation({message:'새 행사로 시작할까요? 저장된 행사는 삭제하지 않습니다.',action:()=>reset(false)})} onReset={()=>setConfirmation({message:'기본정보를 유지하고 상품·수량·광고 계획을 초기화할까요?',action:()=>reset(true)})} onCopy={copy} onLoad={id=>setConfirmation({message:'현재 화면 대신 저장된 행사를 불러올까요?',action:()=>{loadPlan(id)}})} onConfirm={()=>setConfirmation({message:'현재 조건과 계산 결과를 확정할까요? 확정 후에는 복사해서 편집할 수 있습니다.',action:()=>{save(true)}})}/><div className="actions saved-plans"><select aria-label="저장된 행사" value={loadId} onChange={x=>setLoadId(x.target.value)}><option value="">저장된 행사 선택</option>{savedPlans.map(p=><option key={p.id} value={p.id}>{p.channel} · {p.title}</option>)}</select><button className="btn" disabled={!loadId} onClick={()=>loadPlan()}>불러오기</button></div><section id="event-info" className="panel"><div className="section-head"><div><h2>01. 행사 정보 입력</h2><p className="muted">채널 선택 시 RAW의 수수료 기준을 적용하고 원본 행사 시트로 이동할 수 있습니다.</p></div><button className="btn primary" disabled={busy} onClick={()=>save()}><Save size={16}/>{busy?'처리 중…':'웹에 저장'}</button></div><div className="fields"><Field label="행사 시작일" type="date" value={e.start} onChange={start=>change({start})}/><Field label="행사 종료일" type="date" value={e.end} onChange={end=>change({end})}/><Field label="시작 시간" type="time" value={e.startTime} onChange={startTime=>change({startTime})}/><Field label="종료 시간" type="time" value={e.endTime} onChange={endTime=>change({endTime})}/><Pick label="채널" value={e.channel} options={channels} onChange={fixedForChannel}/><Field label="행사명" value={e.title} onChange={title=>change({title})}/><Pick label="행사 주기" value={cycle} options={cycleOptions.length?cycleOptions:[cycle]} onChange={cycle=>change({blocks:e.blocks.map(b=>({...b,cycle}))})}/><Pick label="행사 기간 유형" value={period} options={periodOptions.length?periodOptions:[period]} onChange={period=>change({blocks:e.blocks.map(b=>({...b,period}))})}/><Field label="수수료 기준" value={block.basis} onChange={()=>{}} disabled/><Field label="수수료율 (VAT+) %" type="number" value={Math.round(block.fee*10000)/100} onChange={v=>change({blocks:e.blocks.map((b,i)=>i===selected?{...b,fee:v/100}:b)})}/><Field label="할인율 %" type="number" value={Math.round(block.discount*10000)/100} onChange={v=>change({blocks:e.blocks.map((b,i)=>i===selected?{...b,discount:v/100}:b)})}/><Field label="자사 분담률 %" type="number" value={Math.round(block.share*10000)/100} onChange={v=>change({blocks:e.blocks.map((b,i)=>i===selected?{...b,share:v/100}:b)})}/></div></section>
  <section id="product-conditions" className="panel"><h2>03. 상품군 별 행사 조건 확인</h2><div className="fields"><Pick label="제품" value={group} options={e.blocks.map(b=>b.name)} onChange={v=>{setGroup(v);setOption(v.includes('파우치')||v.includes('인박스')||v.includes('바')?'1박스':'1통')}}/><Pick label="구성" value={option} options={compositions} onChange={v=>{setOption(v);setSelectedChoices([]);setSurcharges({});setBulkSurcharge(0);setFlavorQuery('')}}/><span className="fixed-field">가격 가이드<b>{guide?money(guide):'RAW 조건 확인 필요'}</b></span></div><div className="benefit-controls"><Pick label="채널 부담 추가 할인 (-1,000원)" value={channelExtra} options={['X','O']} onChange={setChannelExtra}/><Pick label="상품 증정 (+1,000원)" value={giftExtra} options={['X','O']} onChange={setGiftExtra}/><Pick label="균일가 (+1,000원)" value={uniformExtra} options={['X','O']} onChange={setUniformExtra}/></div><FeeCard plan={e} index={selected} option={option} guide={guide} benefit={benefit} gift={giftExtra==='O'?'상품 증정 (+1,000원)':''}/><button className="btn primary" onClick={openFlavors}><Check size={16}/>맛 선택</button></section>
  {confirmed&&<section id="sales-plan" className="panel"><h2>04. 구성 품목 확인</h2><p className="muted">선택한 맛 구성과 최종 소비자 결제가를 확인하세요.</p><div className="scheme-summary"><div className="scheme-summary-head"><span>제품</span><span>구성 · 맛</span><span>소비자 결제가</span></div>{e.lines.filter(l=>l.source==='스킴 선택').map((l,i)=><div className="scheme-summary-row" key={i}><b>{l.group}</b><span>{l.option}</span><strong>{money(l.price)}</strong></div>)}</div><button className="btn primary next-btn" onClick={()=>{setStage(2);setDetailPage(true);window.scrollTo({top:0,behavior:'instant'})}}>확인 · 운영 계획으로 이동</button></section>}
  <Dialog open={flavorOpen} onOpenChange={setFlavorOpen}><DialogContent className="flavor-modal"><DialogHeader><DialogTitle>맛 구성 선택</DialogTitle><DialogDescription>{group} {option}에 사용할 구성을 여러 개 선택할 수 있습니다.</DialogDescription></DialogHeader><div className="modal-tools"><div className="history-search"><Search size={16}/><input value={flavorQuery} onChange={x=>setFlavorQuery(x.target.value)} placeholder="맛 검색"/></div><button className="btn" onClick={()=>setSelectedChoices(selectedChoices.length===schemeOptions.length?[]:schemeOptions)}>{selectedChoices.length===schemeOptions.length?'전체 해제':'모두 선택'}</button></div><div className="bulk-surcharge"><label>맛 추가금 일괄 입력 <input type="number" min="0" value={bulkSurcharge} onChange={x=>setBulkSurcharge(Math.max(0,Number(x.target.value)||0))}/><em>원</em></label><button className="btn" onClick={()=>{if(!selectedChoices.length){toast.error('먼저 맛 구성을 선택해 주세요.');return}setSurcharges(v=>({...v,...Object.fromEntries(selectedChoices.filter(x=>!isReference(x)).map(x=>[x,bulkSurcharge]))}))}}>선택 항목에 적용</button></div><div className="flavor-list">{visibleOptions.map(choice=>{const checked=selectedChoices.includes(choice),reference=isReference(choice);return <div key={choice} className={`flavor-choice ${checked?'selected':''}`}><label className="flavor-select"><input type="checkbox" checked={checked} onChange={()=>setSelectedChoices(v=>checked?v.filter(x=>x!==choice):[...v,choice])}/><b>{choice}</b></label><label className="surcharge"><small>{reference?'기준 맛':'추가금'}</small><input type="number" min="0" disabled={reference} value={reference?0:(surcharges[choice]||0)} onChange={x=>setSurcharges(v=>({...v,[choice]:Math.max(0,Number(x.target.value)||0)}))}/><em>원</em></label></div>})}</div><DialogFooter><button className="btn primary" onClick={saveSchemes}>선택 저장 · 스킴 확정 ({selectedChoices.length})</button></DialogFooter></DialogContent></Dialog>{confirmationDialog}{stage===0&&<div className="stage-next"><span>다음 단계에서 가격 가이드와 수수료를 확인합니다.</span><button className="btn primary" onClick={()=>{setStage(1);window.scrollTo({top:0,behavior:'smooth'})}}>가격 · 맛 구성으로 →</button></div>}</div></>
}
