"use client";
import {useState,useEffect} from 'react';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import type {Source} from './workspace';
export function RawTable({source}:{source:Source}){
 const [query,setQuery]=useState(''),[page,setPage]=useState(0);
 const columns=Array.from(new Set(source.rows.flatMap(r=>Object.keys(r.cells)))).sort((a,b)=>a.length-b.length||a.localeCompare(b));
 const rows=source.rows.filter(r=>Object.values(r.cells).join(' ').toLowerCase().includes(query.toLowerCase()));
 return <><label className="search"><input aria-label="시트 내용 검색" value={query} placeholder="시트 안에서 검색" onChange={e=>{setQuery(e.target.value);setPage(0)}}/></label><div className="raw-scroll"><Table><TableHeader><TableRow><TableHead>행</TableHead>{columns.map(c=><TableHead key={c}>{c}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.slice(page*60,(page+1)*60).map(r=><TableRow key={r.row}><TableCell>{r.row}</TableCell>{columns.map(c=>{const v=r.cells[c];return <TableCell className={typeof v==='string'&&/^#(REF!|VALUE!|DIV\/0!|N\/A|NAME\?|NUM!)/.test(v)?'error-cell':''} key={c}>{v===undefined?'':typeof v==='number'?v.toLocaleString('ko-KR',{maximumFractionDigits:6}):String(v)}</TableCell>})}</TableRow>)}</TableBody></Table></div><div className="actions" style={{marginTop:16}}><button className="btn" disabled={page===0} onClick={()=>setPage(p=>p-1)}>이전</button><span className="muted">{page+1} / {Math.max(1,Math.ceil(rows.length/60))} · {rows.length}행</span><button className="btn" disabled={(page+1)*60>=rows.length} onClick={()=>setPage(p=>p+1)}>다음</button></div></>;
}
export default function SourceBrowser({sources}:{sources:Source[]}){
 const [archive,setArchive]=useState<any[]>([]),[query,setQuery]=useState(''),[selected,setSelected]=useState<Source|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[file,setFile]=useState('');
 const loadIndex=()=>fetch('/api/sources').then(async r=>{const d:any=await r.json();if(!r.ok)throw Error(d.error);setArchive(d);setError('')}).catch(e=>setError(e.message));
 useEffect(()=>{void loadIndex()},[]);
 async function open(id:string,file:string){setLoading(true);setFile(file);setError('');try{const r=await fetch('/api/sources?id='+id);const d:any=await r.json();if(!r.ok)throw Error(d.error);setSelected(d)}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
 return <><section className="panel"><div className="section-head"><div><h2>728개 원본 시트 보관함</h2><p className="muted">26개 Excel 파일 · 원본 셀 값과 행·열 위치를 보존했습니다.</p></div><div className="actions"><a className="btn" href="/originals/events.zip" download>행사시트 ZIP 다운로드</a><a className="btn" href="/originals/template.xlsx" download>기준 통합문서 다운로드</a></div></div><div className="warning">수식은 원본에 저장된 계산값을 표시합니다. 주황색 셀은 원본 오류입니다. 이미지·메모·수식·서식은 원본 파일에서 확인하세요.</div><label className="search"><input aria-label="원본 파일 및 시트 검색" placeholder="채널, 파일명, 시트명 검색" value={query} onChange={e=>setQuery(e.target.value)}/></label>{loading&&<p role="status" className="notice">원본 시트를 불러오는 중…</p>}{error&&<div className="warning" role="alert">{error}<button className="btn" onClick={loadIndex}>목록 다시 불러오기</button></div>}{archive.map(a=>({...a,sheets:a.sheets.filter((s:any)=>(a.file+' '+s.name).toLowerCase().includes(query.toLowerCase()))})).filter(a=>a.sheets.length).map(a=><details key={a.file} open={query?true:undefined}><summary>{a.file}<span>{a.sheets.length}개 시트</span></summary><div className="archive-grid">{a.sheets.map((s:any)=><button disabled={loading} className="archive-item" key={s.id} onClick={()=>open(s.id,a.file)}><b>{s.name}</b><small>{s.rows}행{s.errors?` · 원본 오류 ${s.errors}셀`:''}</small></button>)}</div></details>)}</section><section className="panel"><h2>자동화 통합문서 원본</h2>{sources.map(s=><details key={s.name}><summary>{s.name}<span>{s.rows.length}행</span></summary><RawTable source={s}/></details>)}</section><Sheet open={!!selected} onOpenChange={o=>{if(!o)setSelected(null)}}><SheetContent style={{width:'95vw',maxWidth:'95vw',overflow:'auto',padding:24}}><SheetHeader><SheetTitle>{selected?.name}</SheetTitle><SheetDescription>{file} · 원본 계산값</SheetDescription></SheetHeader>{selected&&<RawTable key={file+selected.name} source={selected}/>}</SheetContent></Sheet></>;
}

